name: secret access

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name : print secret
        run:  echo "${{secrets.TOP_SECRET}}"
      - name : print secret from env
        env: 
          TOP_SECRET: ${{secrets.TOP_SECRET}}
        run: echo "$TOP_SECRET"
